# conda env create -f environment.yml
name: ecco_pipeline
channels:
  - conda-forge
  - default
dependencies:
  - python=3.7.7
  - pyresample
  - numpy
  - pyyaml
  - netcdf4
  - python-dateutil
  - requests
  - xarray=0.16.2
