# conda env create -f environment.yml
name: ecco_pipeline
channels:
  - conda-forge
  - default
dependencies:
  - python
  - pyresample
  - numpy
  - pyyaml
  - netcdf4
  - python-dateutil
  - requests
  - xarray
  - ecco_v4_py
  - jupyter